### ISSUE TITLE
iOS 10 plus pop up not showing 

### ISSUE THREAD

**Issue by mgiosdev18** [STAR-ZERO/STZPopupView#12]
Pop up not showing when the deployment target is 10.0 or more. I have created custom UIView.

**Comment by STAR-ZERO** [comment]
I can't reproduce it.
Can you show me your code or more information?
Did you reproduce with this repository [example](https://github.com/STAR-ZERO/STZPopupView/tree/master/Example)?

**Comment by STAR-ZERO** [comment]
Let me close.
