### ISSUE TITLE
ways to make background blur

### ISSUE THREAD

**Issue by kohdesmond** [STAR-ZERO/STZPopupView#8]
Hi as above,

any plans to update the features?

Cheers

**Comment by STAR-ZERO** [comment]
I will try it. Please give me some time.

If you have some idea, please send PR 🙇

**Comment by STAR-ZERO** [comment]
Added this feature on version 1.2.0.

See https://github.com/STAR-ZERO/STZPopupView/blob/master/Source/STZPopupViewConfig.swift#L52
